
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - name: Build
        run: |
          echo "Running build..."			 
          go mod tidy
          go build main.go
    
  security:
    name: Security
    runs-on: ubuntu-latest
    needs: build
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./... || true
