name: Pipeline Tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  pipeline-tests:
    name: Pipeline Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPE_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Zig
        run: sudo snap install zig --classic --beta

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create Python Hello World
        run: echo "print('Hello, World!')" > hello.py


      - name: Create Zig Hello World
        run: |
          echo 'const std = @import("std");
          pub fn main() void {
              std.debug.print("Hello, World!\n", .{});
          }' > hello.zig

      - name: Add workflow files
        run: |
          go run main.go zig
          go run main.go python

      - name: Commit and push workflow files
        env:
          token: ${{ secrets.PIPE_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git branch -c temp_pipe || git checkout -b temp_pipe
          
          git add .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml || echo "No changes to commit"
          
          git commit -m "Add temporary workflow files" || echo "No changes to commit"
          
          git push origin temp_pipe || echo "No changes to push"

      - name: Dispatch workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |

          git branch --show-current
          
          echo "Executing workflow python.yml"
          
          gh workflow run python.yml --ref "$(git rev-parse --abbrev-ref HEAD)"
          
          echo "Executing workflow python_format.yml"
          
          gh workflow run python_format.yml --ref "$(git rev-parse --abbrev-ref HEAD)"
          
          echo "Executing workflow zig.yml"
          
          gh workflow run zig.yml --ref "$(git rev-parse --abbrev-ref HEAD)"
          
          echo "Executing workflow zig_format.yml"
          
          gh workflow run zig_format.yml --ref "$(git rev-parse --abbrev-ref HEAD)"

      - name: Delete workflow files and commit
        env:
          token: ${{ secrets.PIPE_TOKEN }}
        run: |
          rm .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml
          git add .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml
          git commit -m "Remove temporary workflow files"
          git push origin temp_pipe
          gh pr close --head temp_pipe