name: Pipeline Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  pipeline-tests:
    name: Pipeline Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Zig
        run: sudo snap install zig --classic --beta

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create Python Hello World
        run: echo "print('Hello, World!')" > hello.py


      - name: Create Zig Hello World
        run: |
          echo 'const std = @import("std");
          pub fn main() void {
              std.debug.print("Hello, World!\n", .{});
          }' > hello.zig

      - name: Add workflow files
        run: |
          ls -la
          go run main.go zig
          go run main.go python

      - name: Commit and push workflow files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml
          git commit -m "Add temporary workflow files"
          git push origin HEAD:${{ github.ref_name }}

      - name: Dispatch workflow runs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run python.yml --repo zachdehooge/pipelinr --ref ${{ github.ref_name }} --field environment=staging
          gh workflow run python_format.yml --repo zachdehooge/pipelinr --ref ${{ github.ref_name }} --field environment=staging
          gh workflow run zig.yml --repo zachdehooge/pipelinr --ref ${{ github.ref_name }} --field environment=staging
          gh workflow run zig_format.yml --repo zachdehooge/pipelinr --ref ${{ github.ref_name }} --field environment=staging

      - name: Delete workflow files and commit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml
          git add .github/workflows/python.yml .github/workflows/python_format.yml .github/workflows/zig.yml .github/workflows/zig_format.yml
          git commit -m "Remove temporary workflow files"
          git push origin HEAD:${{ github.ref_name }}